# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

install: pip install -r requirements/dev.txt

before_script:
- psql -c 'create database purchasing_test;' -U postgres

script: PYTHONPATH=. nosetests purchasing_test/ -sv --with-coverage --cover-package=purchasing
