"""add metrics flag for contracts

Revision ID: 48c578b852fa
Revises: 4775567688de
Create Date: 2016-01-20 17:52:30.849893

"""

# revision identifiers, used by Alembic.
revision = '48c578b852fa'
down_revision = '4775567688de'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'contract', sa.Column(
        'has_metrics',
        sa.Boolean(),
        nullable=False,
        server_default=sa.schema.DefaultClause('true'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'contract', 'has_metrics')
    ### end Alembic commands ###
